# Generated by Django 3.2.5 on 2021-09-30 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pollspartyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('total_votes', models.IntegerField(default=0)),
                ('all_options', models.BooleanField(default=False)),
                ('anyone_options', models.BooleanField(default=False)),
                ('protect', models.BooleanField(default=False)),
                ('expires_in', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='none', max_length=255)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('poll', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token', to='pollspartyapp.poll')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('is_all', models.BooleanField(default=False)),
                ('is_any', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pollspartyapp.poll')),
            ],
        ),
        migrations.CreateModel(
            name='ControlField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_field', models.CharField(default='None', max_length=255)),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='pollspartyapp.option')),
            ],
        ),
    ]
